import Link from "next/link";
import { ArrowLeft, ArrowRight, History, ShieldCheck } from "lucide-react";
import { formatMoney, scenarios } from "@/lib/pricing";
import type { MemoryDecision } from "@/server/memory";
import { OfferContent } from "./offer-content";

function date(value: string) { return `${new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value))} UTC`; }
function signedMoney(value: number) { return `${value >= 0 ? "+" : "−"}${formatMoney(Math.abs(value))}`; }
function AmountChange({ value }: { value: { before: number; after: number; delta: number } }) { return <span>{formatMoney(value.before)} → {formatMoney(value.after)} ({signedMoney(value.delta)})</span>; }
export function MemoryDecisionView({ projectId, decision }: { projectId: string; decision: MemoryDecision }) {
  const status = decision.row.status[0] + decision.row.status.slice(1).toLowerCase();
  return <article className="memory-detail"><Link className="back-link" href={`/projects/${projectId}/memory`}><ArrowLeft size={15} aria-hidden="true" />Project Memory</Link>
    <header className="memory-detail-header"><div><p className="eyebrow">FINAL CLIENT DECISION · REQUEST #{decision.row.requestNumber}</p><h2>{decision.row.title}</h2><p>{date(decision.row.occurredAt)}</p></div><span className={`memory-status memory-${decision.row.status.toLowerCase()}`}>{status}</span></header>
    <section className="memory-panel"><h3>Final decision</h3><p className="source-text">{decision.finalDecisionText}</p><dl className="memory-decision-facts"><div><dt>Agreement effect</dt><dd>{decision.row.changesScope ? "Changed the project agreement" : "No agreement change"}</dd></div><div><dt>Client comment</dt><dd>{decision.clientComment || "No client comment was recorded."}</dd></div>{decision.tags.length > 0 && <div><dt>Tags</dt><dd>{decision.tags.join(", ")}</dd></div>}</dl></section>
    {(decision.supersession.replaces || decision.supersession.replacedBy) && <section className="memory-panel"><h3>Replacement history</h3>{decision.supersession.replaces && <Link href={`/projects/${projectId}/memory/${decision.supersession.replaces.id}`}>Replaces “{decision.supersession.replaces.title}” <ArrowRight size={14} aria-hidden="true" /></Link>}{decision.supersession.replacedBy && <Link href={`/projects/${projectId}/memory/${decision.supersession.replacedBy.id}`}>Replaced by “{decision.supersession.replacedBy.title}” <ArrowRight size={14} aria-hidden="true" /></Link>}</section>}
    <section className="memory-panel"><h3>Frozen client offer</h3><p className="memory-frozen"><ShieldCheck size={15} aria-hidden="true" />This is the exact offer attached to the final decision.</p><OfferContent offer={decision.offer} /></section>
    <section className="memory-panel"><h3>Agreement clauses saved with this decision</h3>{decision.amendmentClauses.length ? <div className="saved-clauses">{decision.amendmentClauses.map(clause => <div className="saved-clause" id={`clause-${clause.id}`} key={clause.id}><span className="clause-id">{clause.id}</span><p className="source-text">{clause.text}</p></div>)}</div> : <p>No amendment clauses were added by this decision.</p>}</section>
    <section className="memory-panel"><h3>Source evidence</h3>{decision.evidence.length ? <div className="memory-evidence">{decision.evidence.map((item, index) => <blockquote key={`${item.taskId}-${item.sourceId}-${index}`}><p className="source-text">{item.quote}</p><Link href={item.href}>{item.sourceType === "baseline_clause" ? "Original baseline" : "Accepted amendment"} · {item.clauseId}{item.historical ? " · historical" : ""}</Link><small>Used for {item.taskTitle}</small></blockquote>)}</div> : <p>No source evidence was recorded for this decision.</p>}</section>
    <section className="memory-panel"><h3>Offer history</h3><div className="memory-offer-history">{decision.offerHistory.map(item => <div key={item.id}><History size={16} aria-hidden="true" /><span><strong>{item.state.replaceAll("_", " ")}</strong><small>{date(item.createdAt)} · Revision {item.approvedRevision} · likely {formatMoney(item.totalChargePaise.likely)}</small></span></div>)}</div></section>
    <section className="memory-panel"><h3>Original AI analysis</h3><p>{decision.original.provenance.provider} · {decision.original.provenance.model} · {decision.original.provenance.promptVersion}</p><p className="field-help">Saved {date(decision.original.createdAt)}</p>{decision.original.analysis.tasks.map(task => <details className="source-details" key={task.id}><summary>{task.title} · {task.classification}</summary><div className="memory-snapshot"><p className="source-text">{task.explanation}</p><p>Hours: {task.estimatedHours.minimum} / {task.estimatedHours.likely} / {task.estimatedHours.maximum}</p></div></details>)}</section>
    <section className="memory-panel"><h3>Saved review revisions</h3>{decision.revisions.map(revision => <details className="source-details" key={revision.id} open={revision.revision === decision.row.approvedRevision}><summary>Revision {revision.revision} · {revision.createdBy} · {date(revision.createdAt)}</summary><div className="memory-snapshot"><p><strong>Edit reason:</strong> {revision.editReason || "No reason was recorded."}</p>{revision.comparison && <div className="revision-diff"><h4>Changes from revision {revision.revision - 1}</h4>{revision.comparison.tasks.length ? <ul>{revision.comparison.tasks.map(change => <li key={`${change.kind}-${change.id}`}>{change.kind}: {change.title}{change.fields.length ? ` · ${change.fields.join(", ")}` : ""}</li>)}</ul> : <p>No task fields changed.</p>}<p>Hourly rate: <AmountChange value={revision.comparison.hourlyRatePaise} /></p><p>Fixed charge: <AmountChange value={revision.comparison.additionalChargePaise} /></p><p>Price range: {scenarios.map(s => <span key={s}>{s} <AmountChange value={revision.comparison!.totalChargePaise[s]} /></span>)}</p></div>}<div className="memory-revision-tasks">{revision.snapshot.analysis.tasks.map(task => <div key={task.id}><strong>{task.title}</strong><span>{task.classification} · {task.estimatedHours.minimum}/{task.estimatedHours.likely}/{task.estimatedHours.maximum} hours</span></div>)}</div></div></details>)}</section>
  </article>;
}
